# Stage 1: Build the web app
FROM node:lts as builder
WORKDIR /app
COPY ./src/react/package*.json ./
COPY ./src/react/yarn.lock ./
RUN yarn install
COPY ./src/react .
RUN yarn build

# Stage 2: Create the production image
FROM nginx:stable-alpine
ADD ./docker/web/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
